const groqService = require('./groqService');

const LEGAL_DISCLAIMER = "\n\nDisclaimer: This information is generated by an AI assistant and is for educational purposes only. It does not constitute professional legal advice. Laws may vary by jurisdiction and situation. Please consult a qualified advocate for advice specific to your case.";

exports.generateLegalInsight = async (queryData) => {
  const { category, subcategory, description, ruleDecision } = queryData;

  const prompt = `
    You are an expert legal AI assistant for Indian Law. 
    Analyze the following legal query.

    Category: ${category}
    Subcategory: ${subcategory}
    User Description: "${description}"
    Rule-Based Insight: ${ruleDecision?.legalNature || 'General Inquiry'}

    Format your response in valid JSON with the following keys:
    {
      "legalInsight": "A clear, professional explanation of the legal situation.",
      "relevantActs": ["List of specific Indian Penal Code (IPC) sections, acts, or laws relevant to this case."],
      "recommendedActions": ["Step-by-step actionable advice for the user to take immediately."],
      "severity": "Low/Medium/High assessment of the urgency."
    }

    Ensure the tone is empathetic but professional.
  `;

  const messages = [
    { role: "system", content: "You are a helpful legal assistant. Always output valid JSON." },
    { role: "user", content: prompt }
  ];

  try {
    const aiResponseRaw = await groqService.getChatCompletion(messages);
    
    // Attempt to parse JSON
    let aiResponse = {};
    const jsonStartIndex = aiResponseRaw.indexOf('{');
    const jsonEndIndex = aiResponseRaw.lastIndexOf('}');
    
    if (jsonStartIndex !== -1 && jsonEndIndex !== -1) {
        const jsonString = aiResponseRaw.substring(jsonStartIndex, jsonEndIndex + 1);
        try {
            aiResponse = JSON.parse(jsonString);
        } catch (parseError) {
            console.error("AI JSON Parse Error:", parseError.message);
            throw new Error("Failed to parse AI response");
        }
    } else {
        throw new Error("No JSON found in AI response");
    }

    // Append Disclaimer to Insight
    if (aiResponse.legalInsight) {
        aiResponse.legalInsight += LEGAL_DISCLAIMER;
    }

    return aiResponse;

  } catch (error) {
    console.error("AI Service Error:", error.message);
    // Fallback response
    return {
        legalInsight: "We could not generate a specific AI analysis at this moment. Please refer to the standard legal guidance provided." + LEGAL_DISCLAIMER,
        relevantActs: [],
        recommendedActions: ["Consult a verified advocate."],
        severity: "Unknown",
        error: true
    };
  }
};
exports.generateLegalResponse = async (question) => {
    const prompt = `
      You are an expert legal AI assistant strictly for Indian Law. 
      A user has asked: "${question}"

      **IMPORTANT GUIDELINES - YOU MUST FOLLOW THESE STRICTLY:**
      1. You must ONLY answer questions related to law, legal matters, legal rights, legal procedures, acts, sections, court processes, legal disputes, crimes, civil matters, constitutional rights, family law, property law, criminal law, corporate law, labor law, consumer protection, or any other topic that falls under the legal domain.
      2. If the user's question is NOT related to law or legal matters (for example: cooking, recipes, general knowledge, science, math, technology, coding, entertainment, sports, health/medical advice, weather, travel tips, personal opinions, creative writing, etc.), you MUST politely decline and respond ONLY with:
         "I'm sorry, but I can only assist with legal questions related to Indian Law. Your question doesn't appear to be related to a legal matter. Please ask me a question about your legal rights, legal procedures, laws, acts, or any legal concern, and I'll be happy to help!"
      3. Do NOT answer any question that is not directly related to law, even if you know the answer.
      4. Do NOT try to find a legal angle in clearly non-legal questions. Only answer genuinely legal queries.
      5. If the question is legal in nature, provide a clear, professional, and empathetic explanation of the legal principles involved.
      6. Include specific Indian Acts, Sections, or relevant laws if applicable.
      7. Suggest step-by-step actions the user can take.
      8. Keep your response concise but helpful.
    `;
  
    const messages = [
      { role: "system", content: "You are a legal-only AI assistant for Indian Law. You must NEVER answer non-legal questions. If a user asks anything unrelated to law, legal rights, legal procedures, acts, or legal matters, you must politely decline and ask them to submit a legal question instead. You must not answer questions about cooking, science, math, coding, entertainment, health, sports, general knowledge, or any other non-legal topic under any circumstances." },
      { role: "user", content: prompt }
    ];
  
    try {
      const response = await groqService.getChatCompletion(messages);
      return response + LEGAL_DISCLAIMER;
    } catch (error) {
      console.error("AI Response Error:", error.message);
      return "We are currently experiencing high traffic. Please try again in a moment." + LEGAL_DISCLAIMER;
    }
};
